spring:
  application:
    name: authorization

  datasource:
    url: jdbc:postgresql://137.184.136.186:5432/bd_principal
    username: admin
    password: "16042004Bb#$19"
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: acme_airlines

server:
  port: 9000

logging:
  level:
    org:
      springframework:
        security: TRACE
